import jsPDF from 'jspdf';

/**
 * Certificate PDF generators.
 *
 * Two flavors:
 *   - generateOwnershipCertificatePDF(gecko, owner)
 *   - generateLineageCertificatePDF({ gecko, sire, dam, grandparents, owner })
 *
 * Both produce a portrait-letter PDF and trigger a download. Pure client
 * side — no server roundtrip. Text-only for now (no embedded photos)
 * because cross-origin image decoding with jsPDF is unreliable; can add
 * images in a follow-up.
 */

function fmtDate(iso) {
  if (!iso) return 'Unknown';
  try {
    return new Date(iso).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return 'Unknown';
  }
}

function timestampSlug() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

// Shared chrome: outer double border, header logo/title, footer
function drawChrome(doc, title, owner) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;

  // Outer double border (emerald-ish)
  doc.setDrawColor(86, 107, 95);
  doc.setLineWidth(1.5);
  doc.rect(margin, margin, pageW - margin * 2, pageH - margin * 2);
  doc.setLineWidth(0.4);
  doc.rect(margin + 3, margin + 3, pageW - margin * 2 - 6, pageH - margin * 2 - 6);

  // Header
  doc.setTextColor(86, 107, 95);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  const breederName = owner?.breeder_name || owner?.full_name || owner?.email || 'GECK INSPECT';
  doc.text(breederName, pageW / 2, margin + 18, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  doc.text(title.toUpperCase(), pageW / 2, margin + 25, { align: 'center' });

  // Decorative line under title
  doc.setDrawColor(86, 107, 95);
  doc.setLineWidth(0.5);
  doc.line(pageW / 2 - 40, margin + 28, pageW / 2 + 40, margin + 28);

  return { pageW, pageH, margin };
}

function drawFooter(doc, geckoId, pageW, pageH, margin) {
  const y = pageH - margin - 10;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Generated by Geck Inspect · geckinspect.com · ${new Date().toLocaleDateString()}`,
    margin + 8,
    y
  );
  doc.text(
    `Certificate ID: CERT-${String(geckoId || '').substring(0, 8).toUpperCase()}`,
    pageW - margin - 8,
    y,
    { align: 'right' }
  );
}

// Section header bar
function drawSectionTitle(doc, text, x, y, width) {
  doc.setFillColor(86, 107, 95);
  doc.rect(x, y, width, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(text.toUpperCase(), x + 3, y + 5);
  return y + 11;
}

// Label + value row
function drawField(doc, label, value, x, y, maxW = 75) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(String(label).toUpperCase(), x, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  const safe = value == null || value === '' ? '—' : String(value);
  const lines = doc.splitTextToSize(safe, maxW);
  doc.text(lines[0] || '—', x, y + 5);
  return y + 11;
}

function fieldGrid(doc, fields, startX, startY, colWidth, gap = 4) {
  let col = 0;
  let row = 0;
  const perRow = 2;
  fields.forEach(({ label, value }) => {
    const x = startX + col * (colWidth + gap);
    const y = startY + row * 13;
    drawField(doc, label, value, x, y, colWidth - 2);
    col++;
    if (col >= perRow) {
      col = 0;
      row++;
    }
  });
  return startY + (row + (col > 0 ? 1 : 0)) * 13;
}

function drawSubjectBlock(doc, gecko, margin, pageW, y) {
  const blockW = pageW - margin * 2 - 16;
  y = drawSectionTitle(doc, 'Subject Information', margin + 8, y, blockW);

  // Gecko name, large
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(40, 40, 40);
  doc.text(gecko.name || 'Unnamed Gecko', margin + 10, y + 5);
  y += 11;

  // Two-column grid of details
  const colW = (blockW - 8) / 2;
  y = fieldGrid(
    doc,
    [
      { label: 'ID Code', value: gecko.gecko_id_code },
      { label: 'Sex', value: gecko.sex },
      { label: 'Hatch Date', value: fmtDate(gecko.hatch_date) },
      { label: 'Species', value: gecko.species || 'C. ciliatus' },
      { label: 'Weight', value: gecko.weight_grams != null ? `${gecko.weight_grams} g` : null },
      { label: 'Status', value: gecko.status },
    ],
    margin + 10,
    y,
    colW
  );

  // Morphs / notes — full width
  if (gecko.morphs_traits) {
    y = drawField(doc, 'Morphs & Traits', gecko.morphs_traits, margin + 10, y, blockW - 4);
  }
  if (gecko.notes) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text('NOTES', margin + 10, y);
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    const notesLines = doc.splitTextToSize(gecko.notes, blockW - 4);
    const clipped = notesLines.slice(0, 3);
    doc.text(clipped, margin + 10, y + 5);
    y += 5 + clipped.length * 5;
  }
  return y + 4;
}

function drawBreederBlock(doc, owner, margin, pageW, y) {
  const blockW = pageW - margin * 2 - 16;
  y = drawSectionTitle(doc, 'Breeder Information', margin + 8, y, blockW);
  const colW = (blockW - 8) / 2;
  const fields = [
    { label: 'Breeder', value: owner?.breeder_name || owner?.full_name || owner?.email },
    { label: 'Email', value: owner?.email_contact || owner?.email },
  ];
  if (owner?.phone_contact) fields.push({ label: 'Phone', value: owner.phone_contact });
  if (owner?.website_url) fields.push({ label: 'Website', value: owner.website_url });
  if (owner?.business_name) fields.push({ label: 'Business', value: owner.business_name });
  if (owner?.location) fields.push({ label: 'Location', value: owner.location });
  return fieldGrid(doc, fields, margin + 10, y, colW) + 4;
}

function drawParentageBlock(doc, sire, dam, margin, pageW, y) {
  const blockW = pageW - margin * 2 - 16;
  y = drawSectionTitle(doc, 'Parentage', margin + 8, y, blockW);
  const colW = (blockW - 8) / 2;

  const drawParent = (label, parent, x) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text(label, x, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text(parent?.name || 'Unknown', x, y + 6);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(`ID: ${parent?.gecko_id_code || '—'}`, x, y + 11);
  };

  drawParent('SIRE (Father)', sire, margin + 10);
  drawParent('DAM (Mother)', dam, margin + 10 + colW + 4);
  return y + 18;
}

function drawGrandparentageBlock(doc, { gsS, gdS, gsD, gdD }, margin, pageW, y) {
  if (!gsS && !gdS && !gsD && !gdD) return y;
  const blockW = pageW - margin * 2 - 16;
  y = drawSectionTitle(doc, 'Grandparentage', margin + 8, y, blockW);
  const colW = (blockW - 12) / 4;

  const draw = (label, g, x) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text(label.toUpperCase(), x, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    const name = g?.name || 'Unknown';
    doc.text(doc.splitTextToSize(name, colW - 2)[0] || name, x, y + 5);
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text(g?.gecko_id_code || '—', x, y + 10);
  };

  const startX = margin + 10;
  draw('Paternal Grandsire', gsS, startX);
  draw('Paternal Granddam',  gdS, startX + colW + 4);
  draw('Maternal Grandsire', gsD, startX + (colW + 4) * 2);
  draw('Maternal Granddam',  gdD, startX + (colW + 4) * 3);
  return y + 16;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generateOwnershipCertificatePDF(gecko, owner) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  const { pageW, pageH, margin } = drawChrome(doc, 'Certificate of Ownership', owner);

  let y = margin + 40;
  y = drawSubjectBlock(doc, gecko, margin, pageW, y);
  y = drawBreederBlock(doc, owner, margin, pageW, y);

  // Attestation text
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(70, 70, 70);
  const attestation =
    `This certifies that the gecko described above is owned by ${
      owner?.breeder_name || owner?.full_name || owner?.email || 'the undersigned'
    } as of ${new Date().toLocaleDateString()}.`;
  const lines = doc.splitTextToSize(attestation, pageW - margin * 2 - 20);
  doc.text(lines, margin + 10, y + 4);

  drawFooter(doc, gecko.id, pageW, pageH, margin);
  doc.save(`ownership-certificate-${gecko.gecko_id_code || gecko.name || timestampSlug()}.pdf`);
}

export function generateLineageCertificatePDF({ gecko, sire, dam, grandparents = {}, owner }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  const { pageW, pageH, margin } = drawChrome(doc, 'Certificate of Lineage', owner);

  let y = margin + 40;
  y = drawSubjectBlock(doc, gecko, margin, pageW, y);
  y = drawBreederBlock(doc, owner, margin, pageW, y);
  y = drawParentageBlock(doc, sire, dam, margin, pageW, y);
  y = drawGrandparentageBlock(doc, grandparents, margin, pageW, y);

  drawFooter(doc, gecko.id, pageW, pageH, margin);
  doc.save(`lineage-certificate-${gecko.gecko_id_code || gecko.name || timestampSlug()}.pdf`);
}
