import jsPDF from 'jspdf';
import {
  summarizeBreedingHistory,
  breedingHistoryTotals,
} from './breedingHistoryUtils';

/**
 * Certificate PDF generators ,  ownership and lineage.
 *
 * Two flavors, both portrait Letter, both downloaded as a blob via a
 * manual <a> click (the same pattern exportUtils.js uses for the gecko
 * roster CSV/PDF, which is known to work in production browsers).
 *
 * The drawing logic is intentionally simple: pure text + a few rectangles
 * + horizontal divider lines. No complex field grids, no foreign font
 * loading, no Unicode characters that jsPDF's WinAnsi-encoded helvetica
 * can't render. Anything weird in user-entered data is run through
 * safeText() before reaching doc.text().
 */

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fmtDate(value) {
  if (!value) return 'Unknown';
  try {
    const d = value instanceof Date ? value : new Date(value);
    if (isNaN(d.getTime())) return 'Unknown';
    return d.toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return 'Unknown';
  }
}

// jsPDF's standard helvetica is WinAnsi-encoded; smart quotes, dashes,
// emoji, ellipses can break the encoder. Scrub everything before it
// reaches doc.text().
function safeText(value) {
  if (value == null) return '';
  return String(value)
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/[\u2026]/g, '...')
    .replace(/[^\x20-\x7E]/g, '');
}

function safeFilename(value) {
  if (!value) return 'certificate';
  return (
    String(value)
      .replace(/[^a-zA-Z0-9._-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'certificate'
  );
}

// Manual blob download ,  same pattern exportUtils.js uses successfully.
// Doesn't depend on jsPDF's doc.save() implementation.
function downloadPdfBlob(doc, filename) {
  const blob = doc.output('blob');
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ---------------------------------------------------------------------------
// Drawing primitives ,  kept simple on purpose
// ---------------------------------------------------------------------------

function drawHeader(doc, title, owner) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;

  // Outer border (single rect, no double-line decoration)
  doc.setDrawColor(86, 107, 95);
  doc.setLineWidth(1.2);
  doc.rect(margin, margin, pageW - margin * 2, pageH - margin * 2);

  // Breeder name centered at top
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(86, 107, 95);
  const breederName = safeText(
    owner?.breeder_name || owner?.full_name || owner?.email || 'GECK INSPECT'
  );
  doc.text(breederName, pageW / 2, margin + 18, { align: 'center' });

  // Certificate title underneath
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(60, 60, 60);
  doc.text(safeText(title.toUpperCase()), pageW / 2, margin + 27, { align: 'center' });

  // Decorative divider line
  doc.setDrawColor(86, 107, 95);
  doc.setLineWidth(0.5);
  doc.line(pageW / 2 - 50, margin + 31, pageW / 2 + 50, margin + 31);

  return { pageW, pageH, margin };
}

function drawFooter(doc, geckoId, pageW, pageH, margin) {
  const y = pageH - margin - 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    safeText(`Generated by Geck Inspect | geckinspect.com | ${new Date().toLocaleDateString()}`),
    margin + 5,
    y
  );
  doc.text(
    safeText(`Certificate ID: CERT-${String(geckoId || '').substring(0, 8).toUpperCase()}`),
    pageW - margin - 5,
    y,
    { align: 'right' }
  );
}

// Section heading bar with white text on emerald background
function drawSection(doc, title, x, y, width) {
  doc.setFillColor(86, 107, 95);
  doc.rect(x, y, width, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(safeText(title.toUpperCase()), x + 3, y + 5);
  return y + 11;
}

// Single label/value row
function drawRow(doc, label, value, x, y, maxWidth) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(safeText(label.toUpperCase()), x, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  const text = safeText(value) || '-';
  // Force a single-line clip ,  multi-line wraps would mess up our row math
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines[0] || '-', x, y + 5);
}

// Per-season breeding history table. Renders nothing and returns y unchanged
// when there's no history to show (e.g. male, or no eggs on record).
function drawBreedingHistorySection(doc, history, x, y, width) {
  if (!history) return y;
  const rows = summarizeBreedingHistory(history);
  if (!rows.length) return y;

  y = drawSection(doc, 'Breeding History', x, y, width);

  const totals = breedingHistoryTotals(rows);
  const hatchRatePct =
    totals.hatchRate != null ? `${Math.round(totals.hatchRate * 100)}%` : '-';

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(
    safeText(
      `Lifetime: ${totals.seasons} season${totals.seasons === 1 ? '' : 's'} | ${totals.eggsLaid} laid | ${totals.hatched} hatched | hatch rate ${hatchRatePct}`
    ),
    x + 2,
    y
  );
  y += 6;

  // Column layout ,  season | age | # | laid | hatched | inf/fail | weight
  const cols = [
    { key: 'season', label: 'Season', w: 0.20 },
    { key: 'age', label: 'Age', w: 0.09 },
    { key: 'ordinal', label: '#', w: 0.07 },
    { key: 'laid', label: 'Laid', w: 0.10 },
    { key: 'hatched', label: 'Hatched', w: 0.13 },
    { key: 'failed', label: 'Inf/Fail', w: 0.12 },
    { key: 'weight', label: 'Weight Range', w: 0.29 },
  ];
  const innerW = width - 4;
  let cx = x + 2;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  const headerY = y;
  for (const c of cols) {
    doc.text(safeText(c.label.toUpperCase()), cx, headerY);
    cx += innerW * c.w;
  }
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.line(x + 2, y, x + 2 + innerW, y);
  y += 3;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(30, 30, 30);

  // Newest season first ,  most relevant on a certificate.
  for (const row of [...rows].reverse()) {
    const weight =
      row.weightMin != null && row.weightMax != null
        ? row.weightMin === row.weightMax
          ? `${row.weightMin} g`
          : `${row.weightMin}-${row.weightMax} g`
        : '-';
    const values = [
      row.seasonLabel,
      row.ageYears != null ? `${row.ageYears}y` : '-',
      `#${row.seasonNumber}`,
      String(row.eggsLaid),
      String(row.hatched),
      String(row.failedOrInfertile),
      weight,
    ];
    cx = x + 2;
    values.forEach((v, i) => {
      doc.text(safeText(v), cx, y);
      cx += innerW * cols[i].w;
    });
    y += 6;
  }

  return y + 4;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generateOwnershipCertificatePDF(gecko, owner, opts = {}) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  const { pageW, pageH, margin } = drawHeader(doc, 'Certificate of Ownership', owner);

  const blockW = pageW - margin * 2 - 16;
  const innerX = margin + 8;
  let y = margin + 45;

  // Subject section
  y = drawSection(doc, 'Subject', innerX, y, blockW);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text(safeText(gecko?.name || 'Unnamed Gecko'), innerX + 2, y + 5);
  y += 14;

  // Two-column field grid drawn explicitly
  const colW = (blockW - 8) / 2;
  drawRow(doc, 'ID Code', gecko?.gecko_id_code, innerX + 2, y, colW - 4);
  drawRow(doc, 'Sex', gecko?.sex, innerX + 2 + colW + 4, y, colW - 4);
  y += 12;
  drawRow(doc, 'Hatch Date', fmtDate(gecko?.hatch_date), innerX + 2, y, colW - 4);
  drawRow(doc, 'Species', gecko?.species || 'C. ciliatus', innerX + 2 + colW + 4, y, colW - 4);
  y += 12;
  drawRow(
    doc,
    'Weight',
    gecko?.weight_grams != null ? `${gecko.weight_grams} g` : null,
    innerX + 2,
    y,
    colW - 4
  );
  drawRow(doc, 'Status', gecko?.status, innerX + 2 + colW + 4, y, colW - 4);
  y += 16;

  // Owner section
  y = drawSection(doc, 'Owner', innerX, y, blockW);
  drawRow(
    doc,
    'Owner',
    owner?.breeder_name || owner?.full_name || owner?.email,
    innerX + 2,
    y,
    colW - 4
  );
  drawRow(doc, 'Email', owner?.email, innerX + 2 + colW + 4, y, colW - 4);
  y += 12;
  if (owner?.website_url) {
    drawRow(doc, 'Website', owner.website_url, innerX + 2, y, blockW - 4);
    y += 12;
  }
  y += 8;

  // Breeding history (females only, if any records exist)
  if (gecko?.sex === 'Female' && opts.breedingHistory) {
    y = drawBreedingHistorySection(doc, opts.breedingHistory, innerX, y, blockW);
  }

  // Attestation
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(11);
  doc.setTextColor(70, 70, 70);
  const attestation = safeText(
    `This certifies that ${gecko?.name || 'the gecko described above'} is owned by ${
      owner?.breeder_name || owner?.full_name || owner?.email || 'the undersigned'
    } as of ${new Date().toLocaleDateString()}.`
  );
  const attLines = doc.splitTextToSize(attestation, blockW - 8);
  doc.text(attLines, innerX + 2, y);

  drawFooter(doc, gecko?.id, pageW, pageH, margin);

  const slug = safeFilename(gecko?.gecko_id_code || gecko?.name);
  downloadPdfBlob(doc, `ownership-certificate-${slug}.pdf`);
}

export function generateLineageCertificatePDF({ gecko, sire, dam, grandparents = {}, owner, breedingHistory }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  const { pageW, pageH, margin } = drawHeader(doc, 'Certificate of Lineage', owner);

  const blockW = pageW - margin * 2 - 16;
  const innerX = margin + 8;
  let y = margin + 45;

  // Subject section
  y = drawSection(doc, 'Subject', innerX, y, blockW);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text(safeText(gecko?.name || 'Unnamed Gecko'), innerX + 2, y + 5);
  y += 14;

  const colW = (blockW - 8) / 2;
  drawRow(doc, 'ID Code', gecko?.gecko_id_code, innerX + 2, y, colW - 4);
  drawRow(doc, 'Sex', gecko?.sex, innerX + 2 + colW + 4, y, colW - 4);
  y += 12;
  drawRow(doc, 'Hatch Date', fmtDate(gecko?.hatch_date), innerX + 2, y, colW - 4);
  drawRow(doc, 'Species', gecko?.species || 'C. ciliatus', innerX + 2 + colW + 4, y, colW - 4);
  y += 12;
  drawRow(
    doc,
    'Weight',
    gecko?.weight_grams != null ? `${gecko.weight_grams} g` : null,
    innerX + 2,
    y,
    colW - 4
  );
  drawRow(doc, 'Status', gecko?.status, innerX + 2 + colW + 4, y, colW - 4);
  y += 16;

  // Parentage
  y = drawSection(doc, 'Parentage', innerX, y, blockW);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text('SIRE (Father)', innerX + 2, y);
  doc.text('DAM (Mother)', innerX + 2 + colW + 4, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text(safeText(sire?.name) || 'Unknown', innerX + 2, y + 6);
  doc.text(safeText(dam?.name) || 'Unknown', innerX + 2 + colW + 4, y + 6);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(`ID: ${safeText(sire?.gecko_id_code) || '-'}`, innerX + 2, y + 11);
  doc.text(`ID: ${safeText(dam?.gecko_id_code) || '-'}`, innerX + 2 + colW + 4, y + 11);
  y += 18;

  // Grandparentage (4 columns)
  const { gsS, gdS, gsD, gdD } = grandparents;
  if (gsS || gdS || gsD || gdD) {
    y = drawSection(doc, 'Grandparentage', innerX, y, blockW);
    const quarterW = (blockW - 12) / 4;
    const labels = ['Pat. Grandsire', 'Pat. Granddam', 'Mat. Grandsire', 'Mat. Granddam'];
    const gp = [gsS, gdS, gsD, gdD];
    for (let i = 0; i < 4; i++) {
      const x = innerX + 2 + i * (quarterW + 4);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(120, 120, 120);
      doc.text(safeText(labels[i].toUpperCase()), x, y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      const name = safeText(gp[i]?.name) || 'Unknown';
      const lines = doc.splitTextToSize(name, quarterW - 2);
      doc.text(lines[0] || name, x, y + 5);
      doc.setFontSize(7);
      doc.setTextColor(120, 120, 120);
      doc.text(safeText(gp[i]?.gecko_id_code) || '-', x, y + 10);
    }
    y += 16;
  }

  // Breeding history (females only, if any records exist)
  if (gecko?.sex === 'Female' && breedingHistory) {
    y = drawBreedingHistorySection(doc, breedingHistory, innerX, y, blockW);
  }

  // Owner section
  y += 4;
  y = drawSection(doc, 'Owner', innerX, y, blockW);
  drawRow(
    doc,
    'Owner',
    owner?.breeder_name || owner?.full_name || owner?.email,
    innerX + 2,
    y,
    colW - 4
  );
  drawRow(doc, 'Email', owner?.email, innerX + 2 + colW + 4, y, colW - 4);

  drawFooter(doc, gecko?.id, pageW, pageH, margin);

  const slug = safeFilename(gecko?.gecko_id_code || gecko?.name);
  downloadPdfBlob(doc, `lineage-certificate-${slug}.pdf`);
}
