/**
 * Collector templates and the keeper-owned reference stickers.
 * New illustrations are rendered with the same editable card component used
 * by the builder. Reference images retain their live-render fallback.
 */

const KEEPER_REFERENCES = [
  {
    id: 'moonlight',
    image: '/store/custom-stickers/moonlight.webp',
    caption: 'Keeper profile, Moon affinity, two signature moves.',
    note: 'Juvenile life stage with a lineage note, specimen details under the photo, and matchup details along the bottom.',
    design: {
      kind: 'custom_sticker',
      version: 1,
      photo_url: '',
      layout: 'classic',
      border_color: 'yellow',
      stage: 'stage_1',
      evolves_from: 'starlight',
      name: 'Moonlight',
      hp: 100,
      type: 'psychic',
      dex_number: '1',
      height: '12',
      weight: '12',
      attacks: [
        { name: 'Bark', cost: 3, cost_type: 'psychic', damage: '0', text: 'Super cute, not very effective.' },
        { name: 'Scramble', cost: 2, cost_type: 'psychic', damage: '10-', text: 'Confuses the enemy. Small chance of losing her tail.' },
      ],
      weakness_type: 'fighting',
      weakness_multiplier: '×2',
      resistance_type: '',
      resistance_amount: '-30',
      retreat_cost: 3,
      illustrator: 'tennyson',
      set_code: 'SV1',
      card_number: '2',
      set_total: '150',
      rarity: 'common',
      morph_line: 'Lavender Extreme Harlequin',
      size: '3in',
      finish: 'glossy',
    },
  },
  {
    id: 'bat-geck',
    image: '/store/custom-stickers/bat-geck.webp',
    caption: 'Full portrait, silver border, compact details.',
    note: 'The photo runs edge to edge. Name, power score, and affinity sit on top; matchup details and the morph line sit along the bottom.',
    design: {
      kind: 'custom_sticker',
      version: 1,
      photo_url: '',
      layout: 'full_art',
      border_color: 'silver',
      stage: 'stage_1',
      evolves_from: 'geck geck',
      name: 'Bat Geck',
      hp: 100,
      type: 'psychic',
      dex_number: '',
      height: '',
      weight: '',
      attacks: [],
      weakness_type: 'lightning',
      weakness_multiplier: '×2',
      resistance_type: '',
      resistance_amount: '-30',
      retreat_cost: 3,
      illustrator: '',
      set_code: 'SV1',
      card_number: '1',
      set_total: '150',
      rarity: 'common',
      morph_line: 'Dark Base Harlequin',
      size: '3in',
      finish: 'holographic',
    },
  },
];

// These examples use the exact production renderer, so the starting layout
// and the gallery remain in sync. Sample art is never added to an order.
const collectorTemplate = (id, name, type, border, note, attacks, overrides = {}) => ({
  id,
  note,
  design: {
    ...KEEPER_REFERENCES[0].design,
    theme: 'trading_card',
    version: 2,
    photo_url: `/store/custom-stickers/${id}.webp`,
    layout: 'classic',
    name,
    type,
    border_color: border,
    stage: 'basic',
    evolves_from: '',
    hp: 90,
    dex_number: '',
    height: '',
    weight: '',
    attacks: attacks.map(([name, damage, text], i) => ({ name, damage, text, cost: i + 1, cost_type: type })),
    weakness_type: '',
    resistance_type: '',
    retreat_cost: 1,
    illustrator: '',
    set_code: 'GI26',
    card_number: '1',
    set_total: '3',
    rarity: 'uncommon',
    morph_line: 'Crested gecko',
    finish: 'glossy',
    ...overrides,
  },
});

export const STICKER_EXAMPLES = [
  collectorTemplate('canopy', 'Fern', 'grass', 'yellow',
    'Golden frame, fern greens, and a classic two-move profile. A bright first-edition feel.',
    [['Leaf Leap', '20', 'One perfect jump into the canopy.'], ['Branch Grip', '40', 'Small toes. Unshakeable hold.']]),
  collectorTemplate('ember', 'Cinder', 'fire', 'gold',
    'Warm copper tones and a gold frame, with bold moves and a featured edition mark.',
    [['Warm Up', '20', 'Find the sunniest spot on the branch.'], ['Crest Rush', '60', 'A sudden dash, then a well-earned rest.']],
    { layout: 'modern', hp: 120, stage: 'stage_2', evolves_from: 'Juvenile', card_number: '2', rarity: 'rare' }),
  collectorTemplate('moon', 'Luna', 'psychic', 'silver',
    'Silver edging, lavender ink, and a quiet moonlit portrait. A softer collector palette.',
    [['Moon Walk', '10', 'Explore the leaves after lights out.'], ['Night Pounce', '50', 'A patient hunter makes one quick leap.']],
    { layout: 'full_art', hp: 100, stage: 'stage_1', evolves_from: 'Hatchling', card_number: '3', rarity: 'holo_rare' }),
  ...KEEPER_REFERENCES,
];

/** Load one example into the builder as a starting point. */
export function exampleAsStartingDesign(example) {
  return {
    ...example.design,
    theme: 'trading_card',
    photo_url: '',
    photo_path: '',
    name: '',
    morph_line: '',
    attacks: (example.design.attacks || []).map((attack) => ({ ...attack })),
    finish: 'glossy',
  };
}
