import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabaseClient';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  CheckCircle2,
  Circle,
  Clock,
  ExternalLink,
  Plus,
  RefreshCw,
  Sparkles,
  Trash2,
  Loader2,
  ListChecks,
  Filter,
} from 'lucide-react';

/**
 * Admin Tasks — single source of truth for "things I have to do."
 *
 * Three sources mix in one list:
 *   - launch:  one-time launch checklist seeded by migration
 *   - auto:    generated by scanning data (affiliate items missing
 *              partner tags, POD items missing Printful variant IDs,
 *              feature flags off in production, etc.)
 *   - manual:  ad-hoc tasks the admin types in
 *
 * Auto-generation is triggered by a button. It upserts on
 * source_key so re-runs converge — current issues stay pending,
 * resolved issues get auto-completed when the underlying data is
 * fixed.
 */

const CATEGORY_LABEL = {
  launch: 'Launch checklist',
  auto: 'Auto-generated',
  manual: 'Manual',
  misc: 'Other',
};

const STATUS_ORDER = { pending: 0, in_progress: 1, done: 2, skipped: 3 };

function emptyForm() {
  return { title: '', description_md: '', link_url: '', link_label: '', priority: 50 };
}

async function generateAutoTasks() {
  // Pull every signal we can spot client-side, then upsert one task per
  // unresolved issue. Resolved issues (e.g., partner tag now set) get
  // marked 'done' if a corresponding task row exists.
  const findings = []; // { source_key, title, description_md, link_url, link_label, priority }
  const resolvedKeys = new Set();

  // 1. Affiliate items that still need partner tags
  const { data: needTagRows } = await supabase
    .from('store_products')
    .select('id, slug, name, status, fulfillment_mode, vendor_product_url, vendor_extra')
    .eq('fulfillment_mode', 'affiliate_redirect')
    .neq('status', 'archived');
  for (const p of needTagRows || []) {
    const flagged = p.vendor_extra?.needs_partner_tag === true;
    const key = `aff_needs_tag:${p.slug}`;
    if (flagged) {
      findings.push({
        source_key: key,
        title: `Replace placeholder URL with tagged affiliate link: ${p.name}`,
        description_md:
          `Affiliate product **${p.name}** still has a placeholder vendor_product_url. Replace it with a tagged URL once the partner program is approved, then clear \`vendor_extra.needs_partner_tag\`.`,
        link_url: `/AdminPanel`,
        link_label: 'Open store admin',
        priority: 30,
      });
    } else {
      resolvedKeys.add(key);
    }
  }

  // 2. POD items missing a Printful variant ID
  const { data: podRows } = await supabase
    .from('store_products')
    .select('id, slug, name, status, fulfillment_mode, vendor_extra')
    .eq('fulfillment_mode', 'direct_pod')
    .neq('status', 'archived');
  for (const p of podRows || []) {
    const variantId = p.vendor_extra?.printful_variant_id;
    const key = `pod_needs_variant:${p.slug}`;
    if (!variantId) {
      findings.push({
        source_key: key,
        title: `Set Printful variant ID for ${p.name}`,
        description_md:
          `POD product **${p.name}** has no Printful variant ID yet. Upload the design to Printful, copy the variant ID into \`vendor_extra.printful_variant_id\`, set \`our_cost_cents\` from Printful's quote, then activate.`,
        link_url: `https://www.printful.com/dashboard`,
        link_label: 'Open Printful',
        priority: 40,
      });
    } else {
      resolvedKeys.add(key);
    }
  }

  // 3. Draft products that have a real image and a tag/variant — ready to activate
  const { data: draftRows } = await supabase
    .from('store_products')
    .select('id, slug, name, status, fulfillment_mode, images, vendor_extra')
    .eq('status', 'draft');
  for (const p of draftRows || []) {
    const hasImage = Array.isArray(p.images) && p.images.length > 0;
    const ready =
      (p.fulfillment_mode === 'affiliate_redirect' && p.vendor_extra?.needs_partner_tag !== true) ||
      (p.fulfillment_mode === 'direct_pod' && Boolean(p.vendor_extra?.printful_variant_id));
    const key = `ready_to_activate:${p.slug}`;
    if (hasImage && ready) {
      findings.push({
        source_key: key,
        title: `Activate ${p.name}`,
        description_md: `Product **${p.name}** is in draft but has all the prerequisites set. Flip status to \`active\` to publish.`,
        link_url: `/AdminPanel`,
        link_label: 'Open store admin',
        priority: 25,
      });
    } else {
      resolvedKeys.add(key);
    }
  }

  // 4. store_enabled feature flag off
  const { data: enabledRow } = await supabase
    .from('app_settings')
    .select('value')
    .eq('key', 'store_enabled')
    .maybeSingle();
  const storeEnabled = enabledRow?.value === true;
  const enabledKey = 'flag_store_enabled_off';
  if (!storeEnabled) {
    findings.push({
      source_key: enabledKey,
      title: 'Flip store_enabled to true',
      description_md:
        'Master kill-switch is currently off. The Supplies tab is hidden until this flips. Confirm everything else (active products, partner tags, Stripe secrets) is in place before enabling.',
      link_url: '/AdminPanel',
      link_label: 'Open store admin',
      priority: 90,
    });
  } else {
    resolvedKeys.add(enabledKey);
  }

  // 5. Product analytics dashboards configured?
  const { data: dashRow } = await supabase
    .from('app_settings')
    .select('value')
    .eq('key', 'posthog_dashboards')
    .maybeSingle();
  const dashboards = Array.isArray(dashRow?.value) ? dashRow.value : [];
  const dashKey = 'posthog_no_dashboards';
  if (dashboards.length === 0) {
    findings.push({
      source_key: dashKey,
      title: 'Pin at least one PostHog dashboard',
      description_md:
        'Product analytics tab is empty. Build a few starter dashboards in PostHog (DAU, signup funnel, retention) and paste their share-embed URLs into Admin > Product analytics.',
      link_url: '/AdminPanel',
      link_label: 'Open Product analytics',
      priority: 80,
    });
  } else {
    resolvedKeys.add(dashKey);
  }

  // Upsert findings — one row per source_key. on conflict update title +
  // description in case the wording / priority changed, but keep status
  // and notes that the admin may have edited.
  if (findings.length > 0) {
    const rows = findings.map((f) => ({
      source_key: f.source_key,
      category: 'auto',
      title: f.title,
      description_md: f.description_md,
      link_url: f.link_url,
      link_label: f.link_label,
      priority: f.priority,
    }));
    const { error } = await supabase
      .from('admin_tasks')
      .upsert(rows, { onConflict: 'source_key', ignoreDuplicates: false });
    if (error) throw error;
  }

  // Auto-resolve: any auto task whose source_key is in resolvedKeys
  // should flip to done if it's still pending.
  if (resolvedKeys.size > 0) {
    await supabase
      .from('admin_tasks')
      .update({ status: 'done' })
      .in('source_key', Array.from(resolvedKeys))
      .eq('category', 'auto')
      .neq('status', 'done');
  }

  return { created: findings.length, resolved: resolvedKeys.size };
}

function TaskRow({ task, onToggle, onDelete, busy }) {
  const isDone = task.status === 'done';
  const isInProgress = task.status === 'in_progress';
  return (
    <div
      className={`flex items-start gap-3 rounded-md border p-3 transition-colors ${
        isDone
          ? 'border-slate-800 bg-slate-950/40 opacity-60'
          : isInProgress
          ? 'border-amber-700/40 bg-amber-500/5'
          : 'border-slate-700 bg-slate-900/40 hover:border-slate-600'
      }`}
    >
      <button
        onClick={() => onToggle(task)}
        disabled={busy}
        className="mt-0.5 shrink-0"
        title={isDone ? 'Mark pending' : 'Mark done'}
      >
        {isDone ? (
          <CheckCircle2 className="w-5 h-5 text-emerald-400" />
        ) : isInProgress ? (
          <Clock className="w-5 h-5 text-amber-400" />
        ) : (
          <Circle className="w-5 h-5 text-slate-500 hover:text-emerald-300" />
        )}
      </button>
      <div className="flex-1 min-w-0">
        <div className="flex items-start justify-between gap-2">
          <div
            className={`text-sm font-semibold ${
              isDone ? 'text-slate-400 line-through' : 'text-slate-100'
            }`}
          >
            {task.title}
          </div>
          <div className="flex items-center gap-1 shrink-0">
            <span className="text-[10px] uppercase tracking-wider text-slate-500 px-1.5 py-0.5 rounded border border-slate-700">
              {CATEGORY_LABEL[task.category] || task.category}
            </span>
            <Button
              size="sm"
              variant="ghost"
              className="text-slate-500 hover:text-rose-300 h-6 px-1"
              onClick={() => onDelete(task)}
              disabled={busy}
              title="Delete task"
            >
              <Trash2 className="w-3.5 h-3.5" />
            </Button>
          </div>
        </div>
        {task.description_md && (
          <p className="text-xs text-slate-400 mt-1 leading-relaxed whitespace-pre-wrap">
            {task.description_md}
          </p>
        )}
        {task.link_url && (
          <a
            href={task.link_url}
            target={task.link_url.startsWith('http') ? '_blank' : undefined}
            rel={task.link_url.startsWith('http') ? 'noopener noreferrer' : undefined}
            className="inline-flex items-center gap-1 text-xs text-emerald-300 hover:text-emerald-200 mt-2"
          >
            {task.link_label || 'Open link'} <ExternalLink className="w-3 h-3" />
          </a>
        )}
      </div>
    </div>
  );
}

export default function AdminTasks() {
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState('open');
  const [adding, setAdding] = useState(false);
  const [form, setForm] = useState(emptyForm());
  const [autoStatus, setAutoStatus] = useState(null);

  async function load() {
    setLoading(true);
    try {
      const { data, error: e } = await supabase
        .from('admin_tasks')
        .select('*')
        .order('priority', { ascending: true })
        .order('created_date', { ascending: true })
        .limit(500);
      if (e) throw e;
      setTasks(data || []);
    } catch (e) {
      setError(e.message || String(e));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  const grouped = useMemo(() => {
    const filtered = tasks.filter((t) => {
      if (filter === 'open') return t.status === 'pending' || t.status === 'in_progress';
      if (filter === 'done') return t.status === 'done';
      return true;
    });
    filtered.sort((a, b) => {
      const so = (STATUS_ORDER[a.status] ?? 9) - (STATUS_ORDER[b.status] ?? 9);
      if (so !== 0) return so;
      return (a.priority ?? 50) - (b.priority ?? 50);
    });
    const groups = { launch: [], auto: [], manual: [], misc: [] };
    for (const t of filtered) {
      const k = groups[t.category] ? t.category : 'misc';
      groups[k].push(t);
    }
    return groups;
  }, [tasks, filter]);

  async function toggleStatus(task) {
    setBusy(true);
    try {
      const next = task.status === 'done' ? 'pending' : 'done';
      const { error: e } = await supabase
        .from('admin_tasks')
        .update({ status: next })
        .eq('id', task.id);
      if (e) throw e;
      await load();
    } catch (e) {
      setError(e.message || String(e));
    } finally {
      setBusy(false);
    }
  }

  async function deleteTask(task) {
    if (!confirm(`Delete task "${task.title}"?`)) return;
    setBusy(true);
    try {
      const { error: e } = await supabase.from('admin_tasks').delete().eq('id', task.id);
      if (e) throw e;
      await load();
    } catch (e) {
      setError(e.message || String(e));
    } finally {
      setBusy(false);
    }
  }

  async function addManualTask() {
    if (!form.title.trim()) return;
    setBusy(true);
    try {
      const { error: e } = await supabase.from('admin_tasks').insert({
        title: form.title.trim(),
        description_md: form.description_md.trim() || null,
        link_url: form.link_url.trim() || null,
        link_label: form.link_label.trim() || null,
        priority: Number(form.priority) || 50,
        category: 'manual',
      });
      if (e) throw e;
      setForm(emptyForm());
      setAdding(false);
      await load();
    } catch (e) {
      setError(e.message || String(e));
    } finally {
      setBusy(false);
    }
  }

  async function runAuto() {
    setBusy(true);
    setAutoStatus(null);
    setError(null);
    try {
      const out = await generateAutoTasks();
      setAutoStatus(`Sync complete — ${out.created} pending issue${out.created === 1 ? '' : 's'}, ${out.resolved} resolved.`);
      await load();
    } catch (e) {
      setError(e.message || String(e));
    } finally {
      setBusy(false);
      setTimeout(() => setAutoStatus(null), 4000);
    }
  }

  const counts = useMemo(() => ({
    open: tasks.filter((t) => t.status === 'pending' || t.status === 'in_progress').length,
    done: tasks.filter((t) => t.status === 'done').length,
    all: tasks.length,
  }), [tasks]);

  return (
    <div className="space-y-6">
      <Card className="bg-slate-900/50 border-slate-800">
        <CardHeader className="flex flex-row items-start justify-between gap-3">
          <div>
            <CardTitle className="text-white flex items-center gap-2">
              <ListChecks className="w-5 h-5 text-emerald-400" /> Admin tasks
            </CardTitle>
            <p className="text-sm text-slate-400 mt-1 max-w-2xl">
              Single list mixing the launch checklist, auto-generated todos
              from store data, and anything you type in. Tap the circle to
              mark a task done; tap "Auto-generate" to sync the auto group
              against the current state of the catalog.
            </p>
          </div>
          <div className="flex flex-col gap-2 items-end">
            <Button size="sm" onClick={runAuto} disabled={busy} className="bg-emerald-600 hover:bg-emerald-500 text-white">
              {busy ? <Loader2 className="w-4 h-4 mr-1 animate-spin" /> : <Sparkles className="w-4 h-4 mr-1" />}
              Auto-generate
            </Button>
            <Button size="sm" variant="outline" onClick={load} disabled={busy} className="border-slate-700 text-slate-300">
              <RefreshCw className="w-3.5 h-3.5 mr-1" /> Refresh
            </Button>
          </div>
        </CardHeader>
      </Card>

      {error && (
        <div className="rounded-md border border-rose-700/50 bg-rose-950/40 px-4 py-3 text-sm text-rose-200">
          {error}
        </div>
      )}
      {autoStatus && (
        <div className="rounded-md border border-emerald-700/40 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">
          {autoStatus}
        </div>
      )}

      {/* Filter + add */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-1">
          <span className="text-[11px] uppercase tracking-wider text-slate-500 mr-1">
            <Filter className="w-3 h-3 inline" /> Filter
          </span>
          {[
            { id: 'open', label: `Open (${counts.open})` },
            { id: 'done', label: `Done (${counts.done})` },
            { id: 'all', label: `All (${counts.all})` },
          ].map((f) => (
            <button
              key={f.id}
              onClick={() => setFilter(f.id)}
              className={`text-xs px-2.5 py-1 rounded border ${
                filter === f.id
                  ? 'bg-emerald-500/15 text-emerald-300 border-emerald-700/40'
                  : 'bg-slate-900 text-slate-300 border-slate-700 hover:border-slate-600'
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>
        <div className="ml-auto">
          <Button
            size="sm"
            variant="outline"
            className="border-slate-700 text-slate-200 hover:bg-slate-800"
            onClick={() => setAdding((v) => !v)}
          >
            <Plus className="w-3.5 h-3.5 mr-1" /> Add task
          </Button>
        </div>
      </div>

      {adding && (
        <Card className="bg-slate-900/40 border-slate-800">
          <CardContent className="p-4 space-y-3">
            <Input
              placeholder="Task title"
              value={form.title}
              onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))}
              className="bg-slate-950 border-slate-700 text-slate-100"
            />
            <Textarea
              placeholder="Description (markdown ok). What needs to happen, why, and any context."
              value={form.description_md}
              onChange={(e) => setForm((f) => ({ ...f, description_md: e.target.value }))}
              rows={3}
              className="bg-slate-950 border-slate-700 text-slate-100"
            />
            <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
              <Input
                placeholder="Link URL (optional)"
                value={form.link_url}
                onChange={(e) => setForm((f) => ({ ...f, link_url: e.target.value }))}
                className="bg-slate-950 border-slate-700 text-slate-100"
              />
              <Input
                placeholder="Link label (e.g. 'Open Stripe')"
                value={form.link_label}
                onChange={(e) => setForm((f) => ({ ...f, link_label: e.target.value }))}
                className="bg-slate-950 border-slate-700 text-slate-100"
              />
              <Input
                type="number"
                placeholder="Priority (lower = sooner; default 50)"
                value={form.priority}
                onChange={(e) => setForm((f) => ({ ...f, priority: e.target.value }))}
                className="bg-slate-950 border-slate-700 text-slate-100"
              />
            </div>
            <div className="flex justify-end gap-2">
              <Button size="sm" variant="outline" onClick={() => { setAdding(false); setForm(emptyForm()); }} className="border-slate-700 text-slate-300">
                Cancel
              </Button>
              <Button size="sm" disabled={busy || !form.title.trim()} onClick={addManualTask} className="bg-emerald-600 hover:bg-emerald-500 text-white">
                Add task
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {loading ? (
        <div className="flex items-center gap-2 text-slate-400 text-sm">
          <Loader2 className="w-4 h-4 animate-spin" /> Loading…
        </div>
      ) : tasks.length === 0 ? (
        <Card className="bg-slate-900/30 border-dashed border-slate-700">
          <CardContent className="p-8 text-center text-sm text-slate-400">
            No tasks yet. Hit Auto-generate to scan the store, or add one manually.
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6">
          {(['launch', 'auto', 'manual', 'misc']).map((cat) => {
            const items = grouped[cat];
            if (!items || items.length === 0) return null;
            return (
              <div key={cat}>
                <h3 className="text-xs uppercase tracking-wider text-slate-500 mb-2">
                  {CATEGORY_LABEL[cat]} <span className="text-slate-600">({items.length})</span>
                </h3>
                <div className="space-y-2">
                  {items.map((t) => (
                    <TaskRow key={t.id} task={t} onToggle={toggleStatus} onDelete={deleteTask} busy={busy} />
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
