-- Placeholder for migration 20260507211154 (store_seed_vendors_categories_settings).
--
-- This version exists in production's migration history but was applied
-- straight from the Supabase MCP or SQL editor on the day, so the repo
-- never had the file. It is recorded here so `supabase migration list`
-- sees local and remote in step and `supabase db push` never tries to
-- replay it. The objects it created are described in
-- supabase/SCHEMA_SNAPSHOT.md; `supabase db pull` produces the runnable
-- baseline that captures them (docs/MIGRATIONS.md, baselining step 7).
--
-- Intentionally empty. Do not add SQL here.
