import { useState } from 'react';
import IllustratedGecko from '@/components/morphguide/IllustratedGecko';
import PreviousGecko from './SchematicGeckoPrevious';
import { ILLUSTRATED_GECKO_PRESETS, COVERAGE_KEYFRAMES, phenotypeAlong } from '@/components/morphguide/illustratedGeckoPresets';
import PatternSpectrum from '@/components/morphguide/PatternSpectrum';
import StickerCardPreview from '@/components/store/StickerCardPreview';
import StickerCardBefore from './StickerCardBefore';
import { createDefaultDesign } from '@/lib/store/customSticker';
import MorphQuizGlyph, { QUIZ_GLYPHS } from '@/components/morphguide/MorphQuizGlyph';
import DesignReferences from './DesignReferences';

const SAMPLE = { ...createDefaultDesign(), name: 'Fern', photo_crop: { x: 50, y: 50, zoom: 1 }, photo_url: '/store/custom-stickers/collector-classic-art-v4.webp', species_name: 'Crested gecko', morph_line: 'Harlequin. A patient canopy hunter with a remarkable grip.', illustrator: 'Geck Inspect', height: '8 in', weight: '42 g' };
export default function VisualDesignPreview() {
  const [pos, setPos] = useState(2);
  const [selectedMorph, setSelectedMorph] = useState('harlequin');
  const p = phenotypeAlong(COVERAGE_KEYFRAMES, pos);
  return <main className="min-h-screen bg-[#111c19] text-[#eee8d8] px-5 py-12" style={{ fontFamily: 'Arial, sans-serif' }}>
    <div className="max-w-6xl mx-auto space-y-14">
      <header><p className="uppercase tracking-[.24em] text-xs text-emerald-300 mb-3">Geck Inspect · Unpublished design study</p><h1 className="text-4xl sm:text-5xl font-semibold">A collector’s card. A naturalist’s eye.</h1><p className="mt-4 text-stone-400 max-w-3xl">A fresh set of detailed illustrations and researched card frames. Fine ink and dry pencil studies support independent trait layers, with fixed body color and top and side views. This is a review draft, with AI-generated artwork, not a claim of commissioned hand-drawn work.</p><nav className="flex flex-wrap gap-4 mt-5 text-sm text-emerald-300"><a href="#comparison">The new artwork</a><a href="#cards">Collector cards</a><a href="#slider">Animated study</a><a href="#atlas">30-morph atlas</a><a href="#references">Research references</a></nav></header>
      <section id="comparison"><h2 className="text-2xl mb-2 font-semibold">A visibly different illustration.</h2><p className="text-sm text-stone-400 mb-5">Previous schematic on the left. The new fine-ink and dry-pencil study on the right. Slide to compare the coverage examples.</p><div className="grid sm:grid-cols-2 gap-6"><figure className="rounded-xl bg-[#e9e4d3] p-6 flex flex-col justify-center items-center text-[#293c2f]"><PreviousGecko phenotype={p} className="w-full h-auto" /><figcaption className="mt-4">Last preview · Schematic drawing</figcaption></figure><figure className="rounded-xl bg-[#f4efdf] p-3 flex flex-col justify-center items-center text-[#293c2f]"><IllustratedGecko track="coverage" position={pos} className="w-full h-auto" /><figcaption className="mt-4 mb-3">New study · Ink and colored pencil</figcaption></figure></div><label className="block mt-6">Pattern comparison<input aria-label="Before and after pattern coverage" type="range" min="0" max="3" step="0.01" value={pos} onChange={e => setPos(Number(e.target.value))} className="w-full mt-3 accent-emerald-400" /></label><div className="flex justify-between text-xs text-stone-400"><span>Patternless</span><span>Flame</span><span>Harlequin</span><span>Extreme</span></div></section>
      <section id="card-frame-comparison"><h2 className="text-2xl font-semibold mb-2">The card frame, with exactly the same artwork.</h2><p className="text-sm text-stone-400 mb-6">Previous preview and revised frame. Compare the name and HP, basic-stage label, portrait size, attack typography, printed paper texture and flavor border.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-5">{['classic', 'full_art'].flatMap(layout => [<figure key={layout+'before'}><StickerCardBefore design={{ ...SAMPLE, layout }} /><figcaption className="mt-3 text-sm text-stone-400">{layout === 'classic' ? 'Classic' : 'Modern'} · previous</figcaption></figure>, <figure key={layout+'after'}><StickerCardPreview design={{ ...SAMPLE, layout }} /><figcaption className="mt-3 text-sm text-emerald-300">{layout === 'classic' ? 'Classic' : 'Modern'} · revised</figcaption></figure>])}</div></section><section id="cards"><h2 className="text-2xl mb-2 font-semibold">Classic collector and modern illustration card.</h2><p className="text-sm text-stone-400 mb-6">Solid energy stamps, reference-based proportions and compact print typography. Modern artwork runs under the moves and a silver information rail. Every detail is ordinary printed ink; no holographic finish.</p><div className="grid sm:grid-cols-3 gap-8"><figure><StickerCardPreview design={{ ...SAMPLE, type: 'colorless', border_color: 'gold', layout: 'classic' }} /><figcaption className="mt-4 text-stone-400">Classic collector · Natural ivory</figcaption></figure><figure><StickerCardPreview design={{ ...SAMPLE, layout: 'classic' }} /><figcaption className="mt-4">Classic collector · Canopy</figcaption></figure><figure><StickerCardPreview design={{ ...SAMPLE, layout: 'full_art', photo_crop: { x: 50, y: 0, zoom: 1 }, photo_url: '/store/custom-stickers/collector-modern-art-v4.webp' }} /><figcaption className="mt-4">Modern illustration · Matte print</figcaption></figure></div></section>
      <section id="slider"><h2 className="text-2xl mb-5 font-semibold">Try the actual educational slider.</h2><PatternSpectrum /><p className="mt-4 text-sm text-stone-400">The controls combine registered artwork layers. Pinning stays on crest scales, the body color stays fixed, and the two views show different anatomical regions. These are phenotype studies, not breeding predictions.</p></section>
      <section id="atlas"><h2 className="text-2xl mb-2 font-semibold">Pattern studies and specialist examples.</h2><p className="mb-5 text-sm text-stone-400">Common pattern examples use the new ink studies. Specialist morph plates remain from the earlier artwork set and need separate specimen review; conceptual examples retain their existing labels.</p><div className="rounded-xl bg-[#f4efdf] text-[#293c2f] p-4 mb-6"><IllustratedGecko morph={selectedMorph} className="w-full h-auto" /><p className="text-center font-semibold mt-2">{ILLUSTRATED_GECKO_PRESETS[selectedMorph].label}</p></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{Object.entries(ILLUSTRATED_GECKO_PRESETS).map(([slug, preset]) => <button key={slug} onClick={() => setSelectedMorph(slug)} aria-pressed={selectedMorph === slug} className={`rounded-xl bg-[#f4efdf] text-[#293c2f] p-2 flex flex-col items-center border-2 ${selectedMorph === slug ? 'border-emerald-400' : 'border-transparent'}`}><IllustratedGecko morph={slug} decorative className="w-full h-auto" /><span className="mt-2 mb-1 text-xs font-semibold text-center">{preset.label}</span></button>)}</div></section>
      <section id="quiz"><h2 className="text-2xl mb-5 font-semibold">Quiz details use the new painted studies.</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{Object.entries(QUIZ_GLYPHS).flatMap(([step, options]) => Object.entries(options).map(([option, props]) => <figure key={`${step}-${option}`} className="rounded-xl bg-[#f4efdf] text-[#293c2f] p-3"><MorphQuizGlyph {...props} className="w-full h-auto" /><figcaption className="mt-3 text-xs text-center">{step} · {option}</figcaption></figure>))}</div></section>
      <DesignReferences />
    </div>
  </main>;
}
