import { useState } from 'react';
import IllustratedGecko, { STUDY_MORPHS } from '@/components/morphguide/IllustratedGecko';
import { ILLUSTRATED_GECKO_PRESETS } from '@/components/morphguide/illustratedGeckoPresets';
import PatternSpectrum from '@/components/morphguide/PatternSpectrum';
import StickerCardPreview from '@/components/store/StickerCardPreview';
import StickerCardBefore from './StickerCardBefore';
import { createDefaultDesign } from '@/lib/store/customSticker';
import MorphQuizGlyph, { QUIZ_GLYPHS } from '@/components/morphguide/MorphQuizGlyph';
import DesignReferences from './DesignReferences';

const SAMPLE = { ...createDefaultDesign(), name: 'Fern', photo_crop: { x: 50, y: 50, zoom: 1 }, photo_url: '/store/custom-stickers/collector-classic-art-v4.webp', species_name: 'Crested gecko', morph_line: 'Harlequin. A patient canopy hunter with a remarkable grip.', illustrator: 'Geck Inspect', height: '8 in', weight: '42 g' };
export default function VisualDesignPreview() {
  const [selectedMorph, setSelectedMorph] = useState('harlequin');
  return <main className="min-h-screen bg-[#111c19] text-[#eee8d8] px-5 py-12" style={{ fontFamily: 'Arial, sans-serif' }}>
    <div className="max-w-6xl mx-auto space-y-14">
      <header><p className="uppercase tracking-[.24em] text-xs text-emerald-300 mb-3">Geck Inspect · Unpublished design study</p><h1 className="text-4xl sm:text-5xl font-semibold">A field guide for a closer look.</h1><p className="mt-4 text-stone-400 max-w-3xl">Observe real specimens, explore common pattern features, and practice seeing the differences. The new ink-style illustrations keep body color fixed while features change. Unpublished review draft; the illustrations are AI-generated and have not been independently validated by a specialist.</p><nav className="flex flex-wrap gap-4 mt-5 text-sm text-emerald-300"><a href="#slider">Field notebook</a><a href="#cards">Collector cards</a><a href="#atlas">Visible-feature studies</a><a href="#references">Research references</a></nav></header>
      <section id="slider" className="scroll-mt-5"><PatternSpectrum /></section>
      <section id="card-frame-comparison"><h2 className="text-2xl font-semibold mb-2">The card frame, with exactly the same artwork.</h2><p className="text-sm text-stone-400 mb-6">Previous preview and revised frame. Compare the name and HP, basic-stage label, portrait size, attack typography, printed paper texture and flavor border.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-5">{['classic', 'full_art'].flatMap(layout => [<figure key={layout+'before'}><StickerCardBefore design={{ ...SAMPLE, layout }} /><figcaption className="mt-3 text-sm text-stone-400">{layout === 'classic' ? 'Classic' : 'Modern'} · previous</figcaption></figure>, <figure key={layout+'after'}><StickerCardPreview design={{ ...SAMPLE, layout }} /><figcaption className="mt-3 text-sm text-emerald-300">{layout === 'classic' ? 'Classic' : 'Modern'} · revised</figcaption></figure>])}</div></section><section id="cards"><h2 className="text-2xl mb-2 font-semibold">Classic collector and modern illustration card.</h2><p className="text-sm text-stone-400 mb-6">Solid energy stamps, reference-based proportions and compact print typography. Modern artwork runs under the moves and a silver information rail. Every detail is ordinary printed ink; no holographic finish.</p><div className="grid sm:grid-cols-3 gap-8"><figure><StickerCardPreview design={{ ...SAMPLE, type: 'colorless', border_color: 'gold', layout: 'classic' }} /><figcaption className="mt-4 text-stone-400">Classic collector · Natural ivory</figcaption></figure><figure><StickerCardPreview design={{ ...SAMPLE, layout: 'classic' }} /><figcaption className="mt-4">Classic collector · Canopy</figcaption></figure><figure><StickerCardPreview design={{ ...SAMPLE, layout: 'full_art', photo_crop: { x: 50, y: 0, zoom: 1 }, photo_url: '/store/custom-stickers/collector-modern-art-v4.webp' }} /><figcaption className="mt-4">Modern illustration · Matte print</figcaption></figure></div></section>
      <section id="atlas"><h2 className="text-2xl mb-2 font-semibold">A focused set of visible-feature studies.</h2><p className="mb-5 text-sm text-stone-400">These drawings teach locations and coverage. Specialist and disputed traits now use specimen evidence instead of invented diagnostic paintings. The study does not identify genes from appearance.</p><div className="rounded-xl bg-[#f4efdf] text-[#293c2f] p-4 mb-6"><IllustratedGecko morph={selectedMorph} className="w-full h-auto" /><p className="text-center font-semibold mt-2">{ILLUSTRATED_GECKO_PRESETS[selectedMorph].label}</p></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{Object.entries(ILLUSTRATED_GECKO_PRESETS).filter(([slug]) => STUDY_MORPHS.includes(slug)).map(([slug, preset]) => <button key={slug} onClick={() => setSelectedMorph(slug)} aria-pressed={selectedMorph === slug} className={`rounded-xl bg-[#f4efdf] text-[#293c2f] p-2 flex flex-col items-center border-2 ${selectedMorph === slug ? 'border-emerald-400' : 'border-transparent'}`}><IllustratedGecko morph={slug} decorative className="w-full h-auto" /><span className="mt-2 mb-1 text-xs font-semibold text-center">{preset.label}</span></button>)}</div></section>
      <section id="quiz"><h2 className="text-2xl mb-5 font-semibold">Quiz observations, without invented genetic diagnoses.</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{Object.entries(QUIZ_GLYPHS).flatMap(([step, options]) => Object.entries(options).map(([option, props]) => <figure key={`${step}-${option}`} className="rounded-xl bg-[#f4efdf] text-[#293c2f] p-3"><MorphQuizGlyph {...props} className="w-full h-auto" /><figcaption className="mt-3 text-xs text-center">{step} · {option}</figcaption></figure>))}</div></section>
      <DesignReferences />
    </div>
  </main>;
}
