/**
 * Shared route manifest for SEO tooling.
 *
 * Consumed by:
 *   - scripts/build-sitemap.mjs      → emits public/sitemap.xml with <lastmod>
 *   - scripts/prerender.mjs          → emits route-specific static HTML into dist/
 *   - scripts/build-vercel-json.mjs  → emits vercel.json with enumerated SPA
 *                                      rewrites so unknown paths fall through
 *                                      to /404.html (real HTTP 404).
 *
 * Adding a new indexable URL:
 *   1. Append an object here with { path, priority, changefreq, lastmod, meta? }
 *   2. Optionally supply meta { title, description, ogImage } so the
 *      prerenderer can inject it without the route having to render React.
 *   3. Re-run `pnpm build` — sitemap, prerendered HTML, and vercel.json
 *      update together.
 *
 * Morph pages are NOT listed here individually — they're expanded from
 * the canonical MORPHS dataset in src/data/morph-guide.js so adding a
 * new morph automatically lights up a crawlable URL.
 *
 * Authenticated-only pages (Dashboard, Settings, AdminPanel, etc.) are
 * parsed out of src/pages.config.js so that adding a page there stays
 * a one-line change — the SPA rewrite list in vercel.json picks it up
 * automatically on the next build.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

export const SITE_URL = 'https://geckinspect.com';

// Resolve morph slugs from the canonical data file without triggering
// Vite-style imports. We extract slugs with a regex so Node can execute
// this without a bundler in the loop.
function loadMorphSlugs() {
  const src = readFileSync(resolve(REPO_ROOT, 'src/data/morph-guide.js'), 'utf8');
  const matches = [...src.matchAll(/slug:\s*'([a-z0-9-]+)'/g)];
  const slugs = [...new Set(matches.map((m) => m[1]))];
  if (slugs.length === 0) {
    throw new Error('seo-routes: no morph slugs found in src/data/morph-guide.js');
  }
  return slugs;
}

// Resolve blog post entries (slug + title + description + dateModified)
// from src/data/blog-posts.js so every post automatically gets a sitemap
// entry, prerendered HTML, and a vercel.json rewrite. Mirrors the morph
// parser — regex-based to keep the script dependency-free.
function loadBlogPosts() {
  const src = readFileSync(resolve(REPO_ROOT, 'src/data/blog-posts.js'), 'utf8');
  const m = src.match(/export const BLOG_POSTS\s*=\s*\[([\s\S]*?)\n\];/);
  if (!m) return [];
  const body = m[1];
  // Each post block opens with `  {` (two-space indent) and closes
  // with `  },`. Tolerant split — it's a data file we control.
  const entries = body.split(/\n\s{2}\},\s*\n\s{2}\{/).map((c, i, arr) => {
    let x = c;
    if (i === 0) x = x.replace(/^\s*\{\s*/, '');
    if (i === arr.length - 1) x = x.replace(/\s*\}\s*,?\s*$/, '');
    return x;
  });
  const out = [];
  for (const chunk of entries) {
    const gs = (f) => {
      const re = new RegExp(`${f}:\\s*'((?:\\\\.|[^'\\\\])*)'`, 's');
      const hit = chunk.match(re);
      return hit ? hit[1].replace(/\\'/g, "'") : null;
    };
    const slug = gs('slug');
    if (!slug) continue;
    out.push({
      slug,
      title: gs('title'),
      description: gs('description'),
      datePublished: gs('datePublished'),
      dateModified: gs('dateModified') || gs('datePublished'),
    });
  }
  return out;
}

// Resolve CareGuide section ids + titles from the canonical data file.
// Each section becomes its own URL at /CareGuide/<id>, generated by
// src/pages/CareGuideTopic.jsx. We parse the JS source rather than
// importing it to keep this script dependency-free.
function loadCareSections() {
  const src = readFileSync(resolve(REPO_ROOT, 'src/data/care-guide.js'), 'utf8');
  // Grab every `id: '…'` + adjacent `title: '…'` pair inside CARE_CATEGORIES.
  // The category-level entries also have an `id` but no `title`, so we key
  // on "id + title" pairs only (sections always carry a title).
  const out = [];
  const re = /id:\s*'([a-z0-9-]+)',\s*\n\s*title:\s*'([^']+)'/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    out.push({ id: m[1], title: m[2] });
  }
  return out;
}

// ISO-8601 date for sitemap lastmod. Static-content lastmod values live
// with the route; anything that doesn't specify one falls back to today
// at build time.
const TODAY = new Date().toISOString().slice(0, 10);

// Primary landing routes. Priorities follow the "home > guides > tools >
// everything else" hierarchy the audit recommended.
export const STATIC_ROUTES = [
  {
    path: '/',
    priority: 1.0,
    changefreq: 'weekly',
    lastmod: TODAY,
    meta: {
      title: 'Geck Inspect — Crested Gecko Collection, Breeding & Community Platform',
      description:
        'The professional platform for crested gecko breeders and keepers. Track collections, plan breedings, identify morphs with AI, and connect with the community.',
    },
  },
  {
    path: '/About',
    priority: 0.5,
    changefreq: 'yearly',
    lastmod: TODAY,
    meta: {
      title: 'About Geck Inspect',
      description:
        'Geck Inspect is the professional platform for crested gecko (Correlophus ciliatus) breeders and keepers — collection management, breeding planning, AI morph identification, lineage tracking, and community.',
    },
  },
  {
    path: '/Contact',
    priority: 0.4,
    changefreq: 'yearly',
    lastmod: TODAY,
    meta: {
      title: 'Contact Geck Inspect',
      description:
        'Reach the Geck Inspect team for support, content corrections, partnerships, or press about the crested gecko collection and breeding platform.',
    },
  },
  {
    path: '/Terms',
    priority: 0.2,
    changefreq: 'yearly',
    lastmod: '2026-04-17',
    meta: {
      title: 'Terms of Service',
      description:
        'Terms of service governing use of Geck Inspect, the crested gecko tracking, breeding, and community platform.',
    },
  },
  {
    path: '/MarketplaceVerification',
    priority: 0.6,
    changefreq: 'yearly',
    lastmod: '2026-04-17',
    meta: {
      title: 'Marketplace Verification & Trust — Geck Inspect',
      description:
        "How Geck Inspect verifies sellers on the crested gecko marketplace, the Zero's Geckos shipping partnership, buyer protections, and what to check before buying.",
    },
  },
  {
    path: '/PrivacyPolicy',
    priority: 0.2,
    changefreq: 'yearly',
    lastmod: '2026-04-05',
    meta: {
      title: 'Privacy Policy',
      description:
        'How Geck Inspect collects, uses, and protects your personal information when you use the crested gecko tracking and breeding platform.',
    },
  },
  {
    path: '/CareGuide',
    priority: 0.95,
    changefreq: 'monthly',
    lastmod: TODAY,
    meta: {
      title: 'Crested Gecko Care Guide',
      description:
        'Comprehensive crested gecko (Correlophus ciliatus) care guide — housing, temperature and humidity, diet with CGD brand comparison, handling, common health issues, shedding, tail loss, breeding readiness, egg incubation, and hatchling care.',
    },
  },
  {
    path: '/MorphGuide',
    priority: 0.95,
    changefreq: 'weekly',
    lastmod: TODAY,
    meta: {
      title: 'Crested Gecko Morph Guide — Every Known Morph',
      description:
        'Definitive visual and written reference for every known crested gecko (Correlophus ciliatus) morph. Harlequin, Pinstripe, Dalmatian, Lilly White, Cappuccino, Axanthic, and dozens more — with inheritance, rarity, and pricing.',
    },
  },
  {
    path: '/GeneticsGuide',
    priority: 0.9,
    changefreq: 'monthly',
    lastmod: TODAY,
    meta: {
      title: 'Crested Gecko Genetics Guide',
      description:
        'From Punnett squares to proving recessives — the crested gecko genetics guide. Understand Lilly White co-dominance, Cappuccino and Axanthic recessives, Soft Scale dominance, and why most morphs are polygenic.',
    },
  },
  {
    path: '/GeneticCalculatorTool',
    priority: 0.85,
    changefreq: 'monthly',
    lastmod: TODAY,
    meta: {
      title: 'Crested Gecko Genetics Calculator',
      description:
        'Free Punnett-square genetics calculator for crested gecko breeders. Predict offspring outcomes for Lilly White, Cappuccino, Axanthic, and Soft Scale pairings.',
    },
  },
  {
    path: '/MorphVisualizer',
    priority: 0.7,
    changefreq: 'monthly',
    lastmod: TODAY,
  },
  {
    path: '/Gallery',
    priority: 0.8,
    changefreq: 'daily',
    lastmod: TODAY,
  },
  {
    path: '/CommunityConnect',
    priority: 0.7,
    changefreq: 'daily',
    lastmod: TODAY,
  },
  {
    path: '/Forum',
    priority: 0.7,
    changefreq: 'daily',
    lastmod: TODAY,
  },
  {
    path: '/Marketplace',
    priority: 0.8,
    changefreq: 'daily',
    lastmod: TODAY,
  },
  {
    path: '/MarketplaceBuy',
    priority: 0.7,
    changefreq: 'daily',
    lastmod: TODAY,
  },
  {
    path: '/Shipping',
    priority: 0.8,
    changefreq: 'monthly',
    lastmod: TODAY,
  },
  {
    path: '/Giveaways',
    priority: 0.8,
    changefreq: 'daily',
    lastmod: TODAY,
  },
  {
    path: '/Membership',
    priority: 0.6,
    changefreq: 'monthly',
    lastmod: TODAY,
  },
  {
    path: '/AuthPortal',
    priority: 0.3,
    changefreq: 'yearly',
    lastmod: TODAY,
  },
];

// Morph detail pages. Priority weighted by how central the morph is to
// the hobby (Harlequin, Lilly White, Cappuccino rank highest; obscure
// polygenic variants rank lower). Defaulting to 0.7 keeps the long tail
// present without overstating its importance.
const HIGH_VALUE_MORPHS = new Set([
  'harlequin',
  'extreme-harlequin',
  'pinstripe',
  'dalmatian',
  'flame',
  'cappuccino',
  'lilly-white',
  'axanthic',
]);

export function getMorphRoutes() {
  const slugs = loadMorphSlugs();
  return slugs.map((slug) => ({
    path: `/MorphGuide/${slug}`,
    priority: HIGH_VALUE_MORPHS.has(slug) ? 0.9 : 0.7,
    changefreq: 'monthly',
    lastmod: TODAY,
  }));
}

// Morph taxonomy hub pages — one per category and per inheritance
// mode. Small, high-quality hubs that keep the internal link graph
// dense and capture "all recessive crested gecko morphs" style
// queries.
const MORPH_CATEGORIES_META = [
  { id: 'pattern', label: 'Pattern morphs' },
  { id: 'base', label: 'Base color morphs' },
  { id: 'color', label: 'Color modifier morphs' },
  { id: 'structure', label: 'Structural morphs' },
  { id: 'combo', label: 'Combination morphs' },
];

const MORPH_INHERITANCES_META = [
  { id: 'recessive', label: 'Recessive crested gecko morphs' },
  { id: 'co-dominant', label: 'Co-dominant crested gecko morphs' },
  { id: 'incomplete-dominant', label: 'Incomplete-dominant crested gecko morphs' },
  { id: 'dominant', label: 'Dominant crested gecko morphs' },
  { id: 'polygenic', label: 'Polygenic crested gecko morphs' },
  { id: 'line-bred', label: 'Line-bred crested gecko morphs' },
];

export function getMorphTaxonomyRoutes() {
  const cats = MORPH_CATEGORIES_META.map(({ id, label }) => ({
    path: `/MorphGuide/category/${id}`,
    priority: 0.8,
    changefreq: 'weekly',
    lastmod: TODAY,
    meta: {
      title: `${label} — Crested Gecko Morph Guide`,
      description: `Every crested gecko ${label.toLowerCase()} in one place — inheritance, rarity, and deep links to per-morph detail pages.`,
    },
  }));
  const inhs = MORPH_INHERITANCES_META.map(({ id, label }) => ({
    path: `/MorphGuide/inheritance/${id}`,
    priority: 0.8,
    changefreq: 'weekly',
    lastmod: TODAY,
    meta: {
      title: label,
      description: `${label} grouped by inheritance mode. Complete list with rarity, visual cues, and links to per-morph detail pages.`,
    },
  }));
  return [...cats, ...inhs];
}

// CareGuide topic pages are programmatically generated from the
// care-guide.js sections. Priority is uniform 0.7 — high enough to keep
// them crawled regularly, not so high that the long tail dominates the
// primary navigation pages (/CareGuide, /MorphGuide, /GeneticsGuide).
export function getCareTopicRoutes() {
  const sections = loadCareSections();
  return sections.map(({ id, title }) => ({
    path: `/CareGuide/${id}`,
    priority: 0.7,
    changefreq: 'monthly',
    lastmod: TODAY,
    meta: {
      title: `${title} — Crested Gecko Care`,
      description: `${title} — part of the Geck Inspect crested gecko (Correlophus ciliatus) care guide.`,
    },
  }));
}

// Blog index + per-post detail routes. The index keeps a high priority
// because it's the topic-cluster hub; individual posts default to 0.75
// so they outrank the long-tail morph pages but stay below the primary
// reference guides.
export function getBlogRoutes() {
  const posts = loadBlogPosts();
  const index = [{
    path: '/blog',
    priority: 0.85,
    changefreq: 'weekly',
    lastmod: posts.reduce(
      (acc, p) => (p.dateModified && p.dateModified > acc ? p.dateModified : acc),
      TODAY,
    ),
    meta: {
      title: 'Crested Gecko Blog',
      description:
        'Long-form crested gecko genetics, breeding, and care articles from the Geck Inspect editorial team — built on the Foundation Genetics consensus.',
    },
  }];
  const posts_ = posts.map((p) => ({
    path: `/blog/${p.slug}`,
    priority: 0.75,
    changefreq: 'monthly',
    lastmod: p.dateModified || TODAY,
    meta: {
      title: p.title,
      description: p.description,
    },
  }));
  return [...index, ...posts_];
}

export function getAllRoutes() {
  return [
    ...STATIC_ROUTES,
    ...getMorphRoutes(),
    ...getMorphTaxonomyRoutes(),
    ...getCareTopicRoutes(),
    ...getBlogRoutes(),
  ];
}

// -----------------------------------------------------------------------
// SPA route enumeration for vercel.json
// -----------------------------------------------------------------------
// These helpers exist so `scripts/build-vercel-json.mjs` can list every
// known SPA path as an explicit rewrite to /index.html. Paths NOT in
// this list fall through to Vercel's default 404 handler, which serves
// /public/404.html with a real HTTP 404 status. Previously the
// catch-all `(.*)` rewrite returned 200 for every unknown path, which
// Bing and some AI crawlers penalize as soft-404.
//
// Source of truth for authenticated pages is src/pages.config.js — we
// parse its PAGES object so adding a route there auto-propagates here.

// Pages that are always rendered inside <AuthenticatedApp> but live at
// /<Key>. The React router mounts `/Home` in the unauthenticated branch
// too, so list it here for completeness.
const AUTH_EXTRA_STATIC_PATHS = ['/Home'];

// Vercel `source` patterns for parametric routes. Specific patterns
// (prefix-disambiguated) are listed before looser ones so that Vercel's
// first-match order doesn't accidentally send `/MorphGuide/category/x`
// into the `/MorphGuide/:slug` rewrite. Vercel matches rewrites in
// order, so keep the ordering hierarchical.
const DYNAMIC_ROUTE_PATTERNS = [
  '/MorphGuide/category/:categoryId',
  '/MorphGuide/inheritance/:inheritanceId',
  '/MorphGuide/:slug',
  '/CareGuide/:topic',
  '/Breeder/:slug',
  '/passport/:passportCode/qr',
  '/passport/:passportCode',
  '/claim/:token',
  '/blog/:slug',
];

function loadAuthenticatedPagePaths() {
  const src = readFileSync(resolve(REPO_ROOT, 'src/pages.config.js'), 'utf8');
  // Extract the `PAGES = { "Key": ... }` block and pull every quoted key.
  // The leading `\n` anchors the match to a line-starting `export` so the
  // JSDoc example at the top of pages.config.js (where `export const PAGES`
  // is prefixed with ` * `) doesn't win the non-greedy match and starve
  // vercel.json of every auth-gated route — that regression 404'd reloads
  // on /MyGeckos, /Breeding, /ForumPost, etc.
  const m = src.match(/\nexport const PAGES\s*=\s*\{([\s\S]*?)\n\}/);
  if (!m) {
    throw new Error('seo-routes: could not find PAGES object in src/pages.config.js');
  }
  const body = m[1];
  const keys = [...body.matchAll(/"([A-Za-z0-9_]+)"\s*:/g)].map((hit) => hit[1]);
  if (keys.length === 0) {
    throw new Error('seo-routes: PAGES object has no entries');
  }
  return [...new Set(keys)].map((k) => `/${k}`);
}

// Ordered list of Vercel `source` patterns covering every SPA path.
// Order: root + root alias → static landing routes → auth-only pages
// (AdminPanel, Dashboard, Settings, …) → programmatic static pages
// (care topics, morph taxonomy, morph details) → parametric patterns
// last so their greedier `:param` matchers don't swallow a specific
// prefix before it's had a chance to match.
export function getAllSpaPathPatterns() {
  const seen = new Set();
  const out = [];
  const push = (path) => {
    if (!seen.has(path)) {
      seen.add(path);
      out.push(path);
    }
  };

  push('/');
  for (const r of STATIC_ROUTES) push(r.path);
  for (const p of AUTH_EXTRA_STATIC_PATHS) push(p);
  for (const p of loadAuthenticatedPagePaths()) push(p);
  for (const r of getMorphTaxonomyRoutes()) push(r.path);
  for (const r of getCareTopicRoutes()) push(r.path);
  for (const r of getMorphRoutes()) push(r.path);
  for (const r of getBlogRoutes()) push(r.path);
  for (const p of DYNAMIC_ROUTE_PATTERNS) push(p);

  return out;
}
