-- =============================================================================
-- admin_tasks — admin-only checklist with manual + auto-generated entries
-- =============================================================================
-- One table for everything in the "what I have to do to launch this"
-- world. Three task sources:
--   launch  — items I seeded once for the current launch (idempotent
--             via source_key = 'launch:<slug>', so re-running this
--             migration doesn't duplicate them)
--   auto    — generated by scanning data: products missing partner
--             tags, POD items missing Printful variant IDs, etc.
--             Keyed by source_key like 'aff_needs_tag:<product_slug>'.
--   manual  — anything the admin types into the "+ Add task" form.
--
-- All RLS gates on profiles.role = 'admin'. The service role bypasses
-- RLS for the auto-generation cron (next phase) if we want to move it
-- server-side.
-- =============================================================================

create table if not exists public.admin_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description_md text,
  category text not null default 'manual'
    check (category in ('launch', 'auto', 'manual', 'misc')),
  source_key text unique,
  status text not null default 'pending'
    check (status in ('pending', 'in_progress', 'done', 'skipped')),
  priority integer not null default 50,
  link_url text,
  link_label text,
  due_date date,
  completed_at timestamptz,
  completed_by uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  notes text
);

create index if not exists admin_tasks_status_idx on public.admin_tasks(status);
create index if not exists admin_tasks_category_idx on public.admin_tasks(category);
create index if not exists admin_tasks_priority_idx on public.admin_tasks(priority);

alter table public.admin_tasks enable row level security;

drop policy if exists "Admins read tasks" on public.admin_tasks;
create policy "Admins read tasks" on public.admin_tasks for select
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists "Admins write tasks" on public.admin_tasks;
create policy "Admins write tasks" on public.admin_tasks for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

create or replace function public.admin_tasks_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_date := now();
  if new.status = 'done' and old.status <> 'done' then
    new.completed_at := coalesce(new.completed_at, now());
  end if;
  if new.status <> 'done' and old.status = 'done' then
    new.completed_at := null;
    new.completed_by := null;
  end if;
  return new;
end;
$$;

drop trigger if exists admin_tasks_touch on public.admin_tasks;
create trigger admin_tasks_touch
  before update on public.admin_tasks
  for each row execute function public.admin_tasks_touch_updated_at();

-- =============================================================================
-- Seed: launch checklist
-- =============================================================================
-- These match the "what you need to do to launch" list from the
-- supplies-store first-iteration delivery, plus a few items I noted
-- for the food-reorder feature. Each task carries a link_url that
-- jumps the admin to the right place.
-- =============================================================================

insert into public.admin_tasks (source_key, category, title, description_md, link_url, link_label, priority)
values
  ('launch:apply-pangea-wholesale',
   'launch',
   'Apply for Pangea wholesale dealer account',
   'Required to flip the seeded Pangea CGD products from affiliate_redirect to dropship_wholesale. The application asks for an EIN / resale certificate and a sample order — usually a few weeks to approve.',
   'https://www.pangeareptile.com/pages/breeder-application-pangea-for-professionals',
   'Open Pangea dealer application', 10),
  ('launch:apply-repashy-wholesale',
   'launch',
   'Apply for Repashy wholesale dealer account',
   'Repashy enforces MAP and forbids dealers from listing on Amazon — note that before applying. The pricing_constraint=''map'' flag on Repashy products will need a map_floor_cents value once approved.',
   'https://www.store.repashy.com/wholesale/',
   'Open Repashy wholesale page', 20),
  ('launch:apply-amazon-associates',
   'launch',
   'Apply for Amazon Associates',
   'Required before any of the seeded `aff-*` Amazon products go live. Once approved, the partner tag goes into store_vendors.affiliate_default_tag for the Amazon vendor row.',
   'https://affiliate-program.amazon.com/',
   'Open Amazon Associates', 30),
  ('launch:apply-chewy-partnerize',
   'launch',
   'Apply for Chewy via Partnerize',
   'Chewy''s $15 new-customer bounty is the best long-tail affiliate rate on the list. Once approved, swap a few of the Amazon picks (Exo Terra, Zoo Med, Fluker''s) over to Chewy URLs.',
   'https://www.chewy.com/app/content/affiliate',
   'Open Chewy affiliate page', 40),
  ('launch:apply-printful',
   'launch',
   'Create the Printful account + upload the 18 tee designs',
   'Each seeded `tee-*` row carries a `vendor_extra.design_brief` describing the design. Upload art, create variants, copy each Printful variant ID into `vendor_extra.printful_variant_id` on the matching product, then set our_cost_cents from Printful''s quote.',
   'https://www.printful.com/dashboard',
   'Open Printful', 50),
  ('launch:set-stripe-secrets',
   'launch',
   'Set STRIPE_SECRET_KEY + STRIPE_WEBHOOK_SECRET on the store edge functions',
   'Both `store-checkout` and `store-stripe-webhook` need these. After deploy, configure the Stripe dashboard webhook to fire on `checkout.session.completed`, `checkout.session.async_payment_succeeded`, `checkout.session.async_payment_failed`, `charge.refunded` against the webhook URL.',
   'https://dashboard.stripe.com/apikeys',
   'Open Stripe API keys', 60),
  ('launch:enable-stripe-tax',
   'launch',
   'Turn on Stripe Tax in the Stripe dashboard',
   'The store-checkout function already passes `automatic_tax[enabled]=true`. Without Stripe Tax enabled in the dashboard, Checkout falls back to no tax calculation. Stripe Tax handles calculation; filing still needs a CPA / TaxJar.',
   'https://dashboard.stripe.com/tax',
   'Open Stripe Tax settings', 70),
  ('launch:configure-resend-from',
   'launch',
   'Verify the EMAIL_FROM domain in Resend',
   'Order receipts (and the existing notifications system) use Resend. Make sure the sending domain is verified before checkout goes live so receipts don''t bounce to spam.',
   'https://resend.com/domains',
   'Open Resend domains', 80),
  ('launch:configure-pg-cron',
   'launch',
   'Confirm pg_cron is enabled and the CGD reminder is scheduled',
   'The `20260507_store_food_reorder.sql` migration enables pg_cron and schedules `cgd_reorder_reminder_daily` at 09:00 UTC. After deploy, run `select * from extensions.cron.job` to confirm. If the project doesn''t allow pg_cron, we''ll convert the daily check into an external HTTP cron.',
   null, null, 85),
  ('launch:flip-store-enabled',
   'launch',
   'Flip store_enabled to true once products are live',
   'Master kill-switch. The Supplies sidebar tab and RecommendedKitForGecko aside both honor this. Toggle from Admin > Store > Settings.',
   '/AdminPanel',
   'Open admin panel', 95),
  ('launch:resale-certificates',
   'launch',
   'File resale certificates for states we''ll ship into',
   'Once Printful is shipping, we should file resale certs to avoid paying sales tax on the wholesale leg. Founder action — not a code task. CPA can advise on which states matter at our scale.',
   null, null, 100),
  ('launch:graphic-design-pass',
   'launch',
   'Design pass on the 18 tee slate',
   'Each tee row has a `vendor_extra.design_brief` slug describing the concept. You''re handling design yourself — track progress here so we know which are ready to upload to Printful.',
   '/AdminPanel',
   'Open store admin', 105),
  ('launch:order-tee-samples',
   'launch',
   'Order one of each tee design as a sample',
   'Real lifestyle photos convert 2–3× the Printful auto-mockups in every POD case study. Replace the auto-mockups on each PDP with photos of the real shirt.',
   null, null, 110),
  ('launch:write-store-faq',
   'launch',
   'Write a Supplies FAQ section + shipping/returns policy',
   'Store > footer links should at minimum cover shipping, returns, and an "is this affiliate?" disclosure. Phase 1 placeholder is fine; flesh out before turning on advertising spend.',
   null, null, 115),
  ('launch:write-gift-seo-copy',
   'launch',
   'Write 400–600 words of intro/outro copy for /Store/c/gifts and the 7 sub-pages',
   'Thin pages won''t rank against existing affiliate-blog sites. Each gift sub-category has `seo_intro_md` and `seo_outro_md` columns waiting for content. Aim for a real human voice — Google''s helpful-content update penalizes generic gift-guide spam.',
   '/Store/c/gifts',
   'Open Gifts hub', 120)
on conflict (source_key) do nothing;
